import esbuild from 'esbuild';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

const prod = process.argv[2] === 'production';

esbuild
  .build({
    banner: {
      js: banner,
    },
    entryPoints: ['src/index.ts'],
    bundle: true,
    external: ['obsidian'],
    format: 'cjs',
    // watch: !prod,
    target: 'es2016',
    outfile: 'main.js',
    sourcemap: prod ? false : 'inline',
    minify: prod,
  })
  .catch(() => process.exit(1));
